### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by Chiff** [codeTom/glstn#9]
cau,

ked urobis nieco zle alert sa ti da az pri nasledujucej akcii, cize ak pri odhlaseni obeda dam zly datum nic nevypise a ked datum opravis obed stranka odhlasi ale az potom sa alert ukaze 
:)

**Comment by codeTom** [comment]
Ahoj,
Dakujem za upozornenie, tiez som si to vsimol, ked budem mat cas sa na to pozrem, ale kludne to mozes fixnut a spravit pull request :)

**Comment by Chiff** [comment]
bohuzial teraz nemam cas ani moc skusenosti pretoze zatial len zacinam takze moc sa ti do toho nechem rypat :) ked si este nieco vsimnem dam ti vediet ale teraz mam dost prace kvoli dizertacke :laughing:
